[package]
name = "libtest-mimic-with-nextest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libtest-mimic = { version = "=0.4.1" }

[[test]]
name = "test"
harness = false
